export const STRATEGIES = {
  sight: [
    {
      id: "s1",
      name: "Sunglasses",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Wear sunglasses to take the edge off bright or harsh light.",
    },
    {
      id: "s11",
      name: "Tinted lenses (FL-41)",
      category: "Reduce",
      type: "Me",
      spoons: 3,
      desc: "Specialist tinted lenses that filter the specific light frequencies most likely to cause discomfort.",
    },
    {
      id: "s12",
      name: "Baseball caps / visors",
      category: "Reduce",
      type: "Me",
      spoons: 2,
      desc: "A brimmed cap blocks overhead light without needing to change your whole environment.",
    },
    {
      id: "s6",
      name: "Dimmer switches",
      category: "Reduce",
      type: "Environment",
      spoons: 3,
      desc: "Dial down overhead lighting to a level that feels comfortable for you.",
    },
    {
      id: "s13",
      name: "Warm lighting instead of cool",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Swap cold white bulbs for warm-toned ones, which are gentler on the eyes.",
    },
    {
      id: "s3",
      name: "Reduce screen brightness",
      category: "Reduce",
      type: "Digital",
      spoons: 1,
      desc: "Lower your screen brightness so it doesn't feel like staring into a light source.",
    },
    {
      id: "s2",
      name: "Dark mode on devices",
      category: "Reduce",
      type: "Digital",
      spoons: 1,
      desc: "Switch to dark mode to reduce the contrast and brightness of your screen.",
    },
    {
      id: "s14",
      name: "Declutter environment",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Clear surfaces and reduce visual noise so your eyes have less to process.",
    },
    {
      id: "s15",
      name: "Plain walls / minimal décor",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Keep walls simple so your environment feels calmer and less busy.",
    },
    {
      id: "s4",
      name: "Close curtains / blackout blinds",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Block out daylight or streetlights when you need a dimmer space.",
    },
    {
      id: "s16",
      name: "Matte screen protectors",
      category: "Reduce",
      type: "Digital",
      spoons: 2,
      desc: "Reduce glare and reflections on your screen with a matte film.",
    },
    {
      id: "s5",
      name: "Turn off overhead lighting",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Switch off harsh overhead lights and use lamps instead.",
    },
    {
      id: "s17",
      name: "Sit facing away from windows",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Position yourself so bright windows aren't in your field of view.",
    },
    {
      id: "s18",
      name: "Reduce movement in field of vision",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Choose a spot where there's less activity, traffic, or flickering around you.",
    },
    {
      id: "s19",
      name: "Adjustable LED lighting",
      category: "Modify",
      type: "Environment",
      spoons: 3,
      desc: "Use smart bulbs you can tune for both warmth and brightness to suit your needs.",
    },
    {
      id: "s20",
      name: "Bias lighting behind screens",
      category: "Modify",
      type: "Environment",
      spoons: 3,
      desc: "Place a soft light behind your monitor to reduce the contrast between screen and room.",
    },
    {
      id: "s21",
      name: "Visual schedules / planners",
      category: "Modify",
      type: "Me",
      spoons: 2,
      desc: "Use visual layouts to make your day more predictable and easier to process.",
    },
    {
      id: "s22",
      name: "Colour coding systems",
      category: "Modify",
      type: "Environment",
      spoons: 2,
      desc: "Assign colours to categories so information is easier to scan at a glance.",
    },
    {
      id: "s7",
      name: "Larger fonts / accessibility",
      category: "Modify",
      type: "Digital",
      spoons: 1,
      desc: "Increase text size so reading takes less effort.",
    },
    {
      id: "s8",
      name: "High contrast modes",
      category: "Modify",
      type: "Digital",
      spoons: 1,
      desc: "Switch to high contrast display settings if standard text feels hard to read.",
    },
    {
      id: "s23",
      name: "Screen filters (blue light)",
      category: "Modify",
      type: "Digital",
      spoons: 2,
      desc: "Apply a filter to reduce the type of light most associated with eye strain.",
    },
    {
      id: "s24",
      name: "Structured layouts (clear zones)",
      category: "Modify",
      type: "Environment",
      spoons: 2,
      desc: "Organise your space into defined areas so it's easier to know where to look.",
    },
    {
      id: "s25",
      name: "Neutral palettes",
      category: "Modify",
      type: "Environment",
      spoons: 2,
      desc: "Decorate with muted, low-saturation colours to keep your environment visually calm.",
    },
    {
      id: "s10",
      name: "Bright colours in environment",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Add vibrant colours to your space if visual stimulation helps you feel alert.",
    },
    {
      id: "s26",
      name: "LED strips / colour-changing lights",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Use colour-changing lights to create an environment that feels engaging or energising.",
    },
    {
      id: "s27",
      name: "Watching visually stimulating content",
      category: "Increase",
      type: "Digital",
      spoons: 1,
      desc: "Put on something visually rich when you need more input to feel regulated.",
    },
    {
      id: "s9",
      name: "Lava lamps / moving light",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Slow, predictable movement in your visual field can be soothing or regulating.",
    },
    {
      id: "s28",
      name: "Patterned décor",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Surround yourself with pattern and texture if visual richness helps you feel grounded.",
    },
    {
      id: "s29",
      name: "Light projectors",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Project moving light patterns onto walls or ceiling for gentle visual stimulation.",
    },
    {
      id: "s30",
      name: "Art / drawing / painting",
      category: "Increase",
      type: "Me",
      spoons: 2,
      desc: "Engage your visual sense actively through making something.",
    },
    {
      id: "s31",
      name: "Fast-paced visual media",
      category: "Increase",
      type: "Digital",
      spoons: 1,
      desc: "Watch something with lots of movement and cuts when you need a stronger visual hit.",
    },
  ],
  sound: [
    {
      id: "so1",
      name: "Noise-cancelling headphones",
      category: "Reduce",
      type: "Me",
      spoons: 2,
      desc: "Block out surrounding sound using active noise-cancellation.",
    },
    {
      id: "so2",
      name: "Earplugs",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Reduce sound levels discreetly — disposable or loop-style.",
    },
    {
      id: "so3",
      name: "Passive ear defenders",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Physical ear defenders to muffle loud or overwhelming environments.",
    },
    {
      id: "so4",
      name: "White noise masking",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Play white noise to cover unpredictable background sounds.",
    },
    {
      id: "so5",
      name: "Turn off background appliances",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Switch off TVs, fans, or hums you've stopped noticing but that are still adding up.",
    },
    {
      id: "so13",
      name: "Close windows",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Shut out traffic, voices, or outdoor sounds.",
    },
    {
      id: "so14",
      name: "Soundproofing (rugs, curtains)",
      category: "Reduce",
      type: "Environment",
      spoons: 3,
      desc: "Use soft furnishings to absorb sound and reduce echo in your space.",
    },
    {
      id: "so12",
      name: "Leave environment early",
      category: "Reduce",
      type: "Me",
      spoons: 2,
      desc: "Give yourself permission to exit a noisy situation before you hit your limit.",
    },
    {
      id: "so6",
      name: "Soundscapes",
      category: "Modify",
      type: "Digital",
      spoons: 1,
      desc: "Natural sounds like rain or birdsong for a calm audio backdrop.",
    },
    {
      id: "so7",
      name: "Pink / brown noise",
      category: "Modify",
      type: "Digital",
      spoons: 1,
      desc: "Soft, steady noise frequency to create a consistent audio environment.",
    },
    {
      id: "so11",
      name: "Spoken word audio",
      category: "Modify",
      type: "Environment",
      spoons: 1,
      desc: "Audiobooks, podcasts, or talk radio in the background for a comfortable spoken word environment.",
    },
    {
      id: "so8",
      name: "Preferred music",
      category: "Increase",
      type: "Digital",
      spoons: 1,
      desc: "Put on music you enjoy to create a sound environment within your control.",
    },
    {
      id: "so9",
      name: "Singing / humming",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Use your own voice — vibration can be deeply calming.",
    },
    {
      id: "so15",
      name: "Instrument playing",
      category: "Increase",
      type: "Me",
      spoons: 3,
      desc: "Play an instrument to engage your auditory sense actively and expressively.",
    },
    {
      id: "so10",
      name: "Clapping / tapping",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Create rhythmic sound with your hands or fingers to regulate.",
    },
  ],
  touch: [
    {
      id: "t1",
      name: "Seamless clothing",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Wear clothing without seams or raised stitching to avoid irritating pressure points.",
    },
    {
      id: "t2",
      name: "Soft fabrics only",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Stick to materials that feel comfortable against your skin, like cotton or bamboo.",
    },
    {
      id: "t3",
      name: "Loose clothing",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Wear relaxed fits that don't press or restrict anywhere on your body.",
    },
    {
      id: "t10",
      name: "Remove tags / labels",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Cut out clothing tags that cause persistent scratching or distraction against your skin.",
    },
    {
      id: "t11",
      name: "Avoid wool / synthetics",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Steer clear of fabrics that feel rough, itchy, or static-prone.",
    },
    {
      id: "t12",
      name: "Protective gloves",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Wear gloves as a barrier when handling materials that feel unpleasant or overwhelming.",
    },
    {
      id: "t13",
      name: "Keep skin dry",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Change out of damp clothing quickly, as moisture against skin can feel intensely uncomfortable.",
    },
    {
      id: "t14",
      name: "Limit physical contact",
      category: "Reduce",
      type: "Me",
      spoons: 2,
      desc: "Set boundaries around touch so you're only receiving contact you've chosen and anticipated.",
    },
    {
      id: "t4",
      name: "Fidget tools",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Keep a small object to hand that gives your fingers something satisfying to do.",
    },
    {
      id: "t15",
      name: "Textured objects",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Use objects with a specific texture to provide controlled, predictable tactile input.",
    },
    {
      id: "t16",
      name: "Compression gloves",
      category: "Modify",
      type: "Me",
      spoons: 2,
      desc: "Wear snug gloves that provide steady, even pressure across your hands.",
    },
    {
      id: "t17",
      name: "Brushing protocols",
      category: "Modify",
      type: "Me",
      spoons: 2,
      desc: "Use a soft sensory brush on your skin to provide deep, regulating tactile input.",
    },
    {
      id: "t6",
      name: "Hand creams / oils",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Apply lotion or oil to your hands for a grounding, predictable tactile experience.",
    },
    {
      id: "t5",
      name: "Weighted lap pads",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Rest a weighted pad across your lap for calming, even pressure while seated.",
    },
    {
      id: "t7",
      name: "Petting animals",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Stroke a pet for soft, warm, and naturally calming tactile input.",
    },
    {
      id: "t8",
      name: "Clay / slime",
      category: "Increase",
      type: "Me",
      spoons: 2,
      desc: "Work with a malleable material that gives satisfying resistance and texture.",
    },
    {
      id: "t9",
      name: "Hand massage",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Massage your own hands to provide deep, controlled pressure to your palms and fingers.",
    },
    {
      id: "t18",
      name: "Sensory bins",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Fill a container with a texture such as rice or sand to explore with your hands.",
    },
    {
      id: "t19",
      name: "Water play",
      category: "Increase",
      type: "Environment",
      spoons: 2,
      desc: "Use running water, a basin, or a bath to engage your sense of touch in a soothing way.",
    },
    {
      id: "t20",
      name: "Exploring textures",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Deliberately handle different surfaces to satisfy the need for varied tactile input.",
    },
    {
      id: "t21",
      name: "Craft activities",
      category: "Increase",
      type: "Me",
      spoons: 2,
      desc: "Use hands-on making such as knitting, beading, or collage to engage your tactile sense.",
    },
  ],
  body: [
    {
      id: "b1",
      name: "Weighted blankets & lap pads",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Deep, even pressure to help your body settle.",
    },
    {
      id: "b2",
      name: "Wall push",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Press palms firmly against a wall and push for 10–30 seconds.",
    },
    {
      id: "b3",
      name: "Compression clothing",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Close-fitting garments providing steady, gentle pressure.",
    },
    {
      id: "b10",
      name: "Tight hugs",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Ask for or give yourself a firm hug to deliver grounding deep pressure.",
    },
    {
      id: "b11",
      name: "Deep pressure massage",
      category: "Calming",
      type: "Me",
      spoons: 2,
      desc: "Slow, firm pressure on muscles to help your nervous system calm down.",
    },
    {
      id: "b12",
      name: "Carrying heavy objects",
      category: "Calming",
      type: "Me",
      spoons: 2,
      desc: "Carry something with real weight for grounding proprioceptive feedback.",
    },
    {
      id: "b13",
      name: "Wall sits",
      category: "Calming",
      type: "Me",
      spoons: 2,
      desc: "Hold a seated position against a wall to engage muscles with steady, calming effort.",
    },
    {
      id: "b6",
      name: "Slow rocking",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Rock your body gently back and forth to soothe your vestibular system.",
    },
    {
      id: "b14",
      name: "Slow walking",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Walk at a deliberate, unhurried pace to provide gentle movement input.",
    },
    {
      id: "b15",
      name: "Lying down after movement",
      category: "Calming",
      type: "Me",
      spoons: 1,
      desc: "Rest flat after activity to let your vestibular system settle and recover.",
    },
    {
      id: "b4",
      name: "Body scan",
      category: "Regulating",
      type: "Me",
      spoons: 1,
      desc: "Mentally move through each part of your body noticing sensation without judgement.",
    },
    {
      id: "b5",
      name: "Stretching",
      category: "Regulating",
      type: "Me",
      spoons: 2,
      desc: "Slowly lengthen muscles to release tension and reconnect with your body.",
    },
    {
      id: "b9",
      name: "Yoga",
      category: "Regulating",
      type: "Me",
      spoons: 3,
      desc: "Poses combining body awareness, breath, and controlled effort.",
    },
    {
      id: "b16",
      name: "Pilates",
      category: "Regulating",
      type: "Me",
      spoons: 3,
      desc: "Controlled, precise movements to build body awareness and calm your nervous system.",
    },
    {
      id: "b17",
      name: "Postural alignment",
      category: "Regulating",
      type: "Me",
      spoons: 1,
      desc: "Adjust how you're sitting or standing to reduce physical tension and feel more grounded.",
    },
    {
      id: "b18",
      name: "Standing still",
      category: "Regulating",
      type: "Me",
      spoons: 1,
      desc: "Plant your feet and stay still for a moment to reset your sense of balance.",
    },
    {
      id: "b19",
      name: "Walking with focus",
      category: "Regulating",
      type: "Me",
      spoons: 2,
      desc: "Walk mindfully, paying attention to each step and your body's movement through space.",
    },
    {
      id: "b20",
      name: "Balance exercises",
      category: "Regulating",
      type: "Me",
      spoons: 2,
      desc: "Practice standing on one foot or using a balance board to regulate through controlled challenge.",
    },
    {
      id: "b7",
      name: "Dancing",
      category: "Alerting",
      type: "Me",
      spoons: 2,
      desc: "Move freely to music for stimulating, joyful vestibular input.",
    },
    {
      id: "b8",
      name: "Jumping",
      category: "Alerting",
      type: "Me",
      spoons: 2,
      desc: "Jump on the spot to send strong input through joints and muscles.",
    },
    {
      id: "b21",
      name: "Running",
      category: "Alerting",
      type: "Me",
      spoons: 3,
      desc: "Move at pace to wake up your vestibular system through speed and rhythm.",
    },
    {
      id: "b22",
      name: "Resistance bursts",
      category: "Alerting",
      type: "Me",
      spoons: 2,
      desc: "Short bursts of pushing or pulling against resistance to quickly raise alertness.",
    },
    {
      id: "b23",
      name: "Fast bodyweight exercise",
      category: "Alerting",
      type: "Me",
      spoons: 3,
      desc: "Move quickly through exercises like squats or press-ups to energise your system.",
    },
    {
      id: "b24",
      name: "Spinning",
      category: "Alerting",
      type: "Me",
      spoons: 2,
      desc: "Turn in circles to deliver strong, activating input to your vestibular system.",
    },
    {
      id: "b25",
      name: "Trampolining",
      category: "Alerting",
      type: "Environment",
      spoons: 3,
      desc: "Bounce repeatedly for strong, repetitive vestibular and proprioceptive input combined.",
    },
  ],
  smell: [
    {
      id: "sm1",
      name: "Fragrance-free products",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Switch to unscented toiletries and cleaning products to remove hidden scent triggers.",
    },
    {
      id: "sm2",
      name: "Ventilation",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Open windows or use a fan to move air through your space and dilute strong smells.",
    },
    {
      id: "sm8",
      name: "Avoid perfumes",
      category: "Reduce",
      type: "Environment",
      spoons: 1,
      desc: "Skip wearing or being around fragranced products that can feel overwhelming.",
    },
    {
      id: "sm9",
      name: "Air purifiers",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Use a purifier to filter out odours and airborne particles from your environment.",
    },
    {
      id: "sm10",
      name: "Mask in strong scents",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Wear a mask in environments where you can't control what you're exposed to.",
    },
    {
      id: "sm7",
      name: "Essential oils",
      category: "Modify",
      type: "Environment",
      spoons: 1,
      desc: "Use a small amount of a familiar scent to create a predictable olfactory environment.",
    },
    {
      id: "sm11",
      name: "Scent rotation",
      category: "Modify",
      type: "Environment",
      spoons: 2,
      desc: "Alternate between scents so your nose doesn't become overloaded by one in particular.",
    },
    {
      id: "sm12",
      name: "Low diffusion",
      category: "Modify",
      type: "Environment",
      spoons: 2,
      desc: "Use a diffuser on a low setting so scent is subtle and doesn't overwhelm the space.",
    },
    {
      id: "sm3",
      name: "Personal scent",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Wear a familiar scent on your wrist or collar so you have a comforting smell close by.",
    },
    {
      id: "sm4",
      name: "Lavender",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Use lavender for its widely recognised calming and grounding scent.",
    },
    {
      id: "sm13",
      name: "Chamomile",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Diffuse or apply chamomile for a soft, soothing scent that supports relaxation.",
    },
    {
      id: "sm14",
      name: "Vanilla",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Use vanilla as a warm, comforting scent that many people find naturally settling.",
    },
    {
      id: "sm15",
      name: "Citrus",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Use citrus scents like orange or lemon for a bright, energising olfactory hit.",
    },
    {
      id: "sm5",
      name: "Peppermint",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Inhale peppermint for a sharp, clarifying scent that can increase alertness.",
    },
    {
      id: "sm16",
      name: "Eucalyptus",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Use eucalyptus for a cooling, clarifying scent that can help you feel more grounded.",
    },
    {
      id: "sm17",
      name: "Coffee smell",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Breathe in coffee aroma for a familiar, alerting scent even without drinking it.",
    },
    {
      id: "sm6",
      name: "Fresh air",
      category: "Increase",
      type: "Environment",
      spoons: 1,
      desc: "Step outside or open a window to clear your olfactory system with clean, neutral air.",
    },
  ],
  taste: [
    {
      id: "ta1",
      name: "Bland foods",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Mild, simple flavours that don't overwhelm your taste receptors.",
    },
    {
      id: "ta2",
      name: "Consistent textures",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Foods with uniform texture — no unexpected mouthfeel surprises.",
    },
    {
      id: "ta3",
      name: "Avoid strong flavours",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Steer clear of heavily seasoned or intensely flavoured foods when already overstimulated.",
    },
    {
      id: "ta4",
      name: "Avoid mixed textures",
      category: "Reduce",
      type: "Me",
      spoons: 1,
      desc: "Skip dishes that combine different textures, like soggy and crunchy together.",
    },
    {
      id: "ta5",
      name: "Chewing gum",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Steady rhythmic oral input that can help regulate your nervous system.",
    },
    {
      id: "ta6",
      name: "Straw drinking",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Drink through a straw for additional oral motor input that many people find calming.",
    },
    {
      id: "ta7",
      name: "Crunchy snacks",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Eat something crunchy to deliver satisfying, regulating input through your jaw.",
    },
    {
      id: "ta8",
      name: "Structured meals",
      category: "Modify",
      type: "Me",
      spoons: 2,
      desc: "Plan your meals in advance so eating feels predictable and low-stress.",
    },
    {
      id: "ta9",
      name: "Predictable eating",
      category: "Modify",
      type: "Me",
      spoons: 1,
      desc: "Stick to familiar foods and routines to reduce the cognitive load around mealtimes.",
    },
    {
      id: "ta10",
      name: "Sour foods",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Sharp, sour flavours like lemon or vinegar for a strong, alerting taste hit.",
    },
    {
      id: "ta11",
      name: "Spicy foods",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Add heat to your food for an intense, activating gustatory experience.",
    },
    {
      id: "ta12",
      name: "Strong flavours",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Choose bold, punchy flavours when you need more input to feel regulated.",
    },
    {
      id: "ta13",
      name: "Cold drinks",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Drink something very cold for a sharp, grounding sensory contrast.",
    },
    {
      id: "ta14",
      name: "Fizzy drinks",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Use carbonation for a strong, stimulating sensation in your mouth and throat.",
    },
    {
      id: "ta15",
      name: "Ice chewing",
      category: "Increase",
      type: "Me",
      spoons: 1,
      desc: "Chew ice for a combined temperature and texture hit that can be intensely grounding.",
    },
  ],
  internal: [
    {
      id: "in7",
      name: "Hunger scale check",
      category: "Hunger",
      type: "Me",
      spoons: 1,
      desc: "Rate your hunger from 1–10 at set times to build awareness before it becomes urgent.",
    },
    {
      id: "in1",
      name: "Regular meal times",
      category: "Hunger",
      type: "Me",
      spoons: 1,
      desc: "Eat at the same times each day so your body doesn't have to send strong signals to remind you.",
    },
    {
      id: "in8",
      name: "Pre-planned meals",
      category: "Hunger",
      type: "Me",
      spoons: 2,
      desc: "Decide what you're eating in advance so hunger doesn't catch you without an easy answer.",
    },
    {
      id: "in9",
      name: "Hourly water reminder",
      category: "Thirst",
      type: "Digital",
      spoons: 1,
      desc: "Set a recurring timer so drinking is triggered by a prompt rather than waiting for a signal.",
    },
    {
      id: "in2",
      name: "Visible water bottle",
      category: "Thirst",
      type: "Me",
      spoons: 1,
      desc: "Keep water in your line of sight so drinking becomes automatic rather than effortful.",
    },
    {
      id: "in10",
      name: "Flavoured water",
      category: "Thirst",
      type: "Me",
      spoons: 1,
      desc: "Add squash or fruit if plain water feels unappealing, so you'll actually drink it.",
    },
    {
      id: "in3",
      name: "Scheduled toilet breaks",
      category: "ToiletNeeds",
      type: "Me",
      spoons: 1,
      desc: "Go at set times throughout the day rather than waiting for a strong urge.",
    },
    {
      id: "in11",
      name: "Body check before transitions",
      category: "ToiletNeeds",
      type: "Me",
      spoons: 1,
      desc: "Make a toilet stop part of your routine before leaving the house or switching activities.",
    },
    {
      id: "in12",
      name: "Temperature check-in",
      category: "Temperature",
      type: "Me",
      spoons: 1,
      desc: "Pause once or twice a day to actively ask yourself whether you're too hot or cold.",
    },
    {
      id: "in4",
      name: "Layered clothing",
      category: "Temperature",
      type: "Me",
      spoons: 1,
      desc: "Dress in layers you can add or remove easily so you can respond quickly when you notice a change.",
    },
    {
      id: "in13",
      name: "Environmental controls",
      category: "Temperature",
      type: "Environment",
      spoons: 1,
      desc: "Keep a fan, blanket, or hot water bottle within reach so adjusting is low-effort.",
    },
    {
      id: "in5",
      name: "Energy rating",
      category: "Fatigue",
      type: "Me",
      spoons: 1,
      desc: "Rate your energy from 1–10 at set points in the day to catch depletion before it becomes a crisis.",
    },
    {
      id: "in14",
      name: "Rest before exhaustion",
      category: "Fatigue",
      type: "Me",
      spoons: 1,
      desc: "Schedule breaks earlier than you think you need them, not after you've already crashed.",
    },
    {
      id: "in15",
      name: "Sleep consistency",
      category: "Fatigue",
      type: "Me",
      spoons: 2,
      desc: "Go to bed and wake at the same time each day to stabilise your baseline energy levels.",
    },
    {
      id: "in16",
      name: "Body location check",
      category: "EmotionBody",
      type: "Me",
      spoons: 1,
      desc: "When you notice a feeling, ask where you feel it physically to help identify what it might be.",
    },
    {
      id: "in6",
      name: "Name it to tame it",
      category: "EmotionBody",
      type: "Me",
      spoons: 1,
      desc: "Putting a word to a physical sensation can reduce its intensity and help you decide what to do next.",
    },
    {
      id: "in17",
      name: "Sensation journal",
      category: "EmotionBody",
      type: "Me",
      spoons: 1,
      desc: "Keep a brief log of physical sensations alongside emotions to learn your own patterns over time.",
    },
  ],
  misc: [
    {
      id: "m1",
      name: "Avoid crowded environments",
      category: "Reduce",
      type: "Environment",
      spoons: 2,
      desc: "Choose quieter venues or times to reduce exposure to noise.",
    },
  ],
};

export const ALL_STRATEGIES = Object.values(STRATEGIES).flat();